# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27832e81e3d3083bbf93bf82fb4ef9b95c17e73bcc797650d88750fe3fc2c295a4be0bd504bf9b19e57d44c3dc1a102113632b4fda2a08094042e5a54269e188

test:
  secret_key_base: 303194574ad3c2607f782012928cbfe77ecf1dea4265c0bd6e672b00406bfa7dddbf98a0c59e11e79fdf259b8a569b09349e5f66aa95b8591542143f3d0da9a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
